---
  - name: start firewalld
    service: name=firewalld state=restarted enabled=yes

  - name: firewalld configuration http
    firewalld: service=http permanent=true state=enabled immediate=yes

  - name: firewalld configuration https
    firewalld: service=https permanent=true state=enabled immediate=yes

  - name: firewalld configuration https
    firewalld: port={{ slaveAgentPort }} permanent=true state=enabled immediate=yes

